### ISSUE TITLE
Using the determinism checker with other classes annotated for the determinism checker

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#11]
The determinism checker defaults fields to `@Det`. This means that constructors have to take `@Det` arguments. As an example, with the following class we get an error in the constructor.
```java
public class Strings {
    public static class StringHolder {
        public String data;

        public StringHolder(String data) {
            this.data = data;
        }
    }

    public static StringHolder makeHolder(String data) {
        return new StringHolder(data);
    }
}
```
This gives the error:
```
Strings.java:6: error: [assignment.type.incompatible] incompatible types in assignment.
            this.data = data;
                        ^
  found   : @PolyDet String
  required: @Det String
```
So, these constructor arguments must be annotated as `@Det`. However, this raises problems when other class use this constructor. There are many instances where we would want to construct a `@NonDet` or `@PolyDet` instance of such a class, but doing so would be impossible because the constructor only takes `@Det` arguments. What we would want would be to be able to create a `@PolyDet StringHolder` from a `@PolyDet String data`. However, this isn't possible, as seen below:
```java
public class Strings {
    public static class StringHolder {
        public String data;

        public StringHolder(@Det String data) {
            this.data = data;
        }
    }

    public static StringHolder makeHolder(String data) {
        return new StringHolder(data);
    }
}
```
which gives the error:
```
Strings.java:8: error: [assignment.type.incompatible] incompatible types in assignment.
            this.data = data;
                        ^
  found   : @PolyDet String
  required: @Det String
```

**Comment by t-rasmud** [comment]
Fixed in 596c390
