### ISSUE TITLE
Annotate all print* methods in PrintStream should be @Det

### ISSUE THREAD

**Issue by smillst** [t-rasmud/checker-framework#110]
Only the println methods require are currently annotated with `@Det`.  The print and printf methods have no explicit annotation, so the default of @PolyDet is applied, which means you can print `@NonDet` expressions.

Also, when using the print*(Object object) methods that take an Object, the checker needs to check that the object.toString() returns `@Det`.

**Comment by t-rasmud** [comment]
Fixed in 6cae5953a44d94b5f0f07765d83ac98e50f4e701
