### ISSUE TITLE
Runtime reflection methods not annotated correctly

### ISSUE THREAD

**Issue by JasonWaataja** [t-rasmud/checker-framework#13]
In `Class.java` in the JDK for the determinism checker, runtime reflection methods such as `getFields` and `getMethods` are annotated as returning `@NonDet Object @NonDet []` where `Field` or `Method` is used instead of `Object`. However, I believe these should be `@Det Object @OrderNonDet []`, as what is in the collection that's returned is deterministic, but the order is not guaranteed.

This would mean that we could get deterministic results by sorting these arrays. For an example, see the `ClassDeterministic` class in the [plume-util library](https://github.com/plume-lib/plume-util).

**Comment by t-rasmud** [comment]
Fixed in [3400922845f7de42405f7d8ba811dc6c8db4738e]()
