### ISSUE TITLE
@HasQualifierParameter shouldn't be allowed on enums, causes erroneous error

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#138]
Currently, the `@HasQualifierParameter` annotation is allowed on enums, which is unnecessary. It also causes the following error when used,
```java
import org.checkerframework.checker.determinism.qual.*;
import org.checkerframework.framework.qual.*;

@HasQualifierParameter(NonDet.class)
public enum E {
    A,
    B
}
```
which gives
```
E.java:6: error: [assignment.type.incompatible] incompatible types in assignment.
    A,
    ^
  found   : @PolyDet E
  required: @Det E
E.java:7: error: [assignment.type.incompatible] incompatible types in assignment.
    B
    ^
  found   : @PolyDet E
  required: @Det E
```

This is a declaration with no assignments so the errors are unexpected. Whatever causes this should be fixed, and the ability for `@HasQualifierParameter` to be written on enums shoudl be removed.

**Comment by t-rasmud** [comment]
Fixed in 96d1c3a7700fc7fe4bee16137f29d307acfb0182
