### ISSUE TITLE
Unsound Iterator.remove() annotation

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#149]
The following code type-checks.
```java
import org.checkerframework.checker.determinism.qual.*;
import java.util.*;

public class IteratorRemove {
    public static void f(@OrderNonDet List<@Det String> list) {
        @OrderNonDet Iterator<@Det String> iter = list.iterator();
        iter.next();
        iter.remove();
    }
}
```

This is unsound for the same reason `List.remove` fails to type check if passed an `@OrderNonDet List`. The element we remove is at index `0` which is non-deterministic in an `@OrderNonDet List` and so afterward the collection would be `@NonDet`.

The fix would be to change the `remove` method in `Iterator` to take `@PolyDet("noOrderNonDet")`.

**Comment by t-rasmud** [comment]
Fixed in 15f3ece3be0f59594730af4a8859fadcfb0b11fa
