### ISSUE TITLE
String.format should have @RequiresDetToString

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#153]
The following code is illegal because the `Object.toString` method can return a non-deterministic result:
```java
static void f(@Det Object o) {
    System.out.printf("%s", o);
}
```
However, the following equivalent code type checks:
```java
import org.checkerframework.checker.determinism.qual.*;

public class C {
    public static void f(@Det Object o) {
        System.out.print(String.format("%s", o));
    }
}
```
Because the `String.format` method can implicitly call `toString` on an arbitrary `Object`, it should also have `@RequiresDetToString`.

**Comment by t-rasmud** [comment]
Fixed in b8f8c6beffae5e50a936b8536c99d4347df4d6b1
