### ISSUE TITLE
@RequiresDetToString should check superclass

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#156]
Consider this code,
```java
import org.checkerframework.checker.determinism.qual.*;

public class Foo {
    public void f(@Det Object o) {
    }

    public static void g() {
        @Det Foo a = new Bar();
        @Det Object o = new Object();
        a.f(o);
    }
}

class Bar extends Foo {
    @RequiresDetToString
    public void f(@Det Object o) {
    }
}
```
This type checks but should not. Because the `f` method in `Bar` has `@RequiresDetToString`, it should be illegal to call it with an `Object` that has a `@NonDet` `toString` method. But, the type checker allows the call in `g` because it's called through a reference of type `Foo`, which doesn't have `@RequiresDetToString`.

The solution is that if a method `f` is overridden and the override is marked with `@RequiresDetToString`, then the superclass version of the method should also be required to have `@RequiresDetToString`.

**Comment by t-rasmud** [comment]
Fixed in 4c138f61650c09927640a984d70b3110770566ef
