### ISSUE TITLE
Incorret entrySet annotation in Map

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#164]
Consider the annotation of the `entrySet` method in `Map`.

```java
 @PolyDet Set<Map.Entry<K, V>> entrySet(@PolyDet Map<K,V> this);
```

Since it's unannotated, in this declaration, the type of each `Entry` is `@Det`. If you had `@NonDet Map<@NonDet String, @NonDet String>`, this would give `@NonDet Set<Map. @Det Entry<@NonDet String, @NonDet String>`, which is an invalid type. The return type should probably be either `@PolyDet Set<Map. @PolyDet Entry<K, V>>` or `@PolyDet Set<Map. @PolyDet("down") Entry<K, V>>` because in an `@OrderNonDet Map` we would want the entries to be `@Det`.

**Comment by t-rasmud** [comment]
Fixed in 3f684c31e051a0caf0ec62188311491f0011e2d0
