### ISSUE TITLE
Unannotated List parameter not handled correctly

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#173]
Consider this class
```java
import org.checkerframework.checker.determinism.qual.*;
import java.util.*;

public class C {
    public static void f(List<@PolyDet String> list) {
        @Det List<@Det String> copy = list;
    }
}
```
I get these errors when type checking,
```
C.java:6: error: [invalid.element.type] element type (@PolyDet) cannot be used with collection type (@Det)
        @Det List<@Det String> copy = list;
                                      ^
C.java:6: error: [assignment.type.incompatible] incompatible types in assignment.
        @Det List<@Det String> copy = list;
                                      ^
  found   : @Det List<@PolyDet String>
  required: @Det List<@Det String>
```

This indicates two problems. The first problem we can see from the second error message is that the type of `list` is `@Det List<@PolyDet String>`. This is incorrect because the default for unannotated method parameters should be `@PolyDet` rather than `@Det`.

The second problem comes from the first error message which says that `list` has an invalid type. This error is only printed when `list` is actually used. There's no error on the declaration of `list` itself. When I remove the one line from the method and run the checker again, there are no errors meaning that `list` is an invalid type but the checker is not flagging it as an error.

**Comment by t-rasmud** [comment]
Fixed in 0dbfbbe471a7674f054c97532d98e7a931fd8e5c
