### ISSUE TITLE
Incorrect annotation on getInterfaces in JDK

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#174]
The method `getInterfaces` in `Class.java` is annotated as,
```java
public @PolyDet Class<?> @PolyDet("upDet") [] getInterfaces(@PolyDet Class<T> this);
```
The return type should be `@PolyDet` rather than `@PolyDet("upDet")` because the documentation for the method specifies that the order of the result is the same as the order the interfaces were declared on the class.

**Comment by t-rasmud** [comment]
Fixed in 503ee67
