### ISSUE TITLE
Nested generics not expanded correctly

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#22]
When a type parameter extends a type that references itself, the checker seems to not accept expressions that it should. In the error message it seems like it does one extra level of recursive expansion on the type parameter on the found type.

Take the following class:
```java
public class NestedGenerics<T extends Comparable<T>> {
    public int compare(T[] a1, T[] a2) {
        return a1[0].compareTo(a2[0]);
    }
}
```
This gives the error:
```
NestedGenerics.java:7: error: [argument.type.incompatible] incompatible types in argument.
        return a1[0].compareTo(a2[0]);
                                 ^
  found   : T extends @PolyDet("") Comparable<T extends @Det Comparable<T extends @Det Comparable<T>>>
  required: T extends @Det Comparable<T extends @Det Comparable<T>>
```

In particular, a1[0] and a2[0] are the same type, `T`, and that type is explicitly `Comparable` to itself. The issue goes away when not using arrays, which might means this might be related to the issue of returning an array of a generic type.

**Comment by t-rasmud** [comment]
Fixed in 498e810
