### ISSUE TITLE
Instruction on how to build non-determinism checker

### ISSUE THREAD

**Issue by xinyuliu12** [t-rasmud/checker-framework#225]
Hi,

First off, I am sorry for gestures vaguely all of this. Second, I was wondering if I could get some help about trying out the non-determinism checker.

Firstly, I was wondering if there exists a way to only build this checker. I try to follow the developer manual to build the entire checker-framework project using the command `./gradlew assemble`, which takes quite a long time. For developers like me who wants to explore the non-determinism checker, is there a more efficient alternative to build this checker? 
Secondly, it would also be useful to have a tutorial on how to use this specific checker.

Thank you very much!

**Comment by mernst** [comment]
Regarding building, you can do something else for an hour while the command completes.

Regarding how to use the checker, please see the manual.  You can build it by running `.gradlew manual`, and then it appears in directory `docs/manual`
