### ISSUE TITLE
@PolyAll doesn't behave like @PolyDet in arrays

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#39]
The `@PolyAll` annotation should be equivalent to adding `@PolyDet` unless something more specific is added, but this is not the case in arrays annotated as `@PolyDet`. When used as the element type on an array explicitly annotated as `@PolyDet`, it is instead resolved to `@Det`. Here, `arr` is a `@Det int @PolyDet []` when it should be `@PolyDet int @PolyDet []`.

### Example
```java
import org.checkerframework.checker.determinism.qual.*;
import org.checkerframework.framework.qual.*;

public class PolyAllDeterminism {
  public static void f(@PolyAll int @PolyDet [] arr) {
    arr = new @PolyDet int @PolyDet[0];
  }
}
```
### Error
```
PolyAllDeterminism.java:6: error: [assignment.type.incompatible] incompatible types in assignment.
    arr = new @PolyDet int @PolyDet[0];
          ^
  found   : @PolyDet int @PolyDet []
  required: @Det int @PolyDet []
```

This only happens when the input array is explicitly annotated as `@PolyDet`. The following code produces no error, as if the default `@PolyDet` took over.
```java
import org.checkerframework.checker.determinism.qual.*;
import org.checkerframework.framework.qual.*;

public class PolyAllDeterminism {
  public static void f(@PolyAll int[] arr) {
    arr = new @PolyDet int @PolyDet[0];
  }
}
```

**Comment by t-rasmud** [comment]
Fixed in 32ee07a
