### ISSUE TITLE
Literals are @NonDet in certain places

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#40]
`String` and `int` literals are always the same across runs, so they should be `@Det`. The Determinism Checker sometimes flags them as `@NonDet` when used inside annotations on locally declared arrays.

### Example
```java
import org.checkerframework.checker.determinism.qual.*;

public class LiteralsBug {
  public static void f() {
    int @PolyDet("up") [] arr;
  }
}
```

### Error
```
LiteralsBug.java:5: error: [annotation.type.incompatible] incompatible types in annotation.
    int @PolyDet("up") [] arr;
                 ^
  found   : @NonDet String
  required: @PolyDet String
```

This error only occurs exactly when a literal is used on the array type in a local declaration. It does not appear when used on the element type, in the expression it's initialized to, or in method signatures.

Two things:
* These literals should be `@Det`.
* Expressions involving annotations should be ignored since they have no effect on execution.

One or both of these should be fixed.

Also, this is not exclusive to `String` literals, it also occurs with `int`s:
```java
import org.checkerframework.common.value.qual.*;

public class LiteralsBug {
  public static void f() {
    int @MinLen(1) [] arr;
  }
}
```
```
LiteralsBug.java:5: error: [annotation.type.incompatible] incompatible types in annotation.
    int @MinLen(1) [] arr;
                ^
  found   : @NonDet int
  required: @PolyDet int
```

**Comment by t-rasmud** [comment]
Fixed in bcbee8e
