### ISSUE TITLE
@PolyDet("use") with parameters and returns

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#50]
When used in type parameters, `@PolyDet("use")` sometimes vanishes when it's required. This makes it so that it can't be used on collections in parameters or returns when there is a method call involved. For example:

```java
import java.util.*;
import org.checkerframework.checker.determinism.qual.*;

public class CarryPolyUse {
  public static <T extends @PolyDet("use") Object> @PolyDet List<T> f(@PolyDet List<T> list) {
    return null;
  }

  public static <T extends @PolyDet("use") Object> @PolyDet List<T> g(@PolyDet List<T> list) {
    return f(list);
  }
}
```
Error:
```
CarryPolyUse.java:10: error: [return.type.incompatible] incompatible types in return.
    return f(list);
            ^
  found   : @PolyDet List<T extends @PolyDet Object>
  required: @PolyDet List<T extends @PolyDet("use") Object>
CarryPolyUse.java:10: error: [argument.type.incompatible] incompatible types in argument.
    return f(list);
             ^
  found   : @PolyDet List<T extends @PolyDet("use") Object>
  required: @PolyDet List<T extends @PolyDet Object>
```

The first error shows that after a method call, `@PolyDet("use")` is dropped when it's required in the return type, despite the fact that it's the same type parameter and should be the same type, and also that since `@PolyDet` and `@PolyDet("use")` are always given the same type, it could be the case that this should be allowed regardless

The second error shows that in the body of a method, the `@PolyDet("use")` on a type parameter disappears when it's required.

**Comment by t-rasmud** [comment]
Fixed in 925bbbc403419f5d5d9a578957d67b3b0d8364c8
