### ISSUE TITLE
Incorrect type while accessing elements of 2 dimensional arrays

### ISSUE THREAD

**Issue by t-rasmud** [t-rasmud/checker-framework#52]
Example:

```
import java.util.ArrayList;
import org.checkerframework.checker.determinism.qual.*;
public class Test2DArrays<T> {
    void testAccess(@Det int @NonDet[] @Det[] arr){
        // :: error: (assignment.type.incompatible)
        @Det int x = arr[0][0];
    }
}
```
Since `arr` is an array of type `@NonDet[@Det[@Det int]]`, accessing its elements should return `@NonDet` and the checker should report an error at the line `@Det int x = arr[0][0];`. But, the checker does not flag any error for the above code.

**Comment by mernst** [comment]
Blocked by https://github.com/typetools/checker-framework/issues/2181
