### ISSUE TITLE
Conditional error message should specify expression type

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#54]
Expressions used in conditional statements are required to be `@Det` but there are many instances where we would want to use, e.g. `@PolyDet` with `@SuppressWarnings`. The error message says that the conditional expression is not `@Det`, but doesn't mention what the actual type is, making it difficult to know when to use `@SuppressWarnings`.

Example:
```java
import org.checkerframework.checker.determinism.qual.*;

public class ConditionalsMessage {
  public static @PolyDet int f(@PolyDet boolean a, @PolyDet int b) {
    return (a) ? b : b;
  }
}
```
Error:
```
ConditionalsMessage.java:5: error: [invalid.type.on.conditional] conditional is not @Det. This will result in non-deterministic behavior
    return (a) ? b : b;
           ^
```

This method is sound, so we would want to use `@SuppressWarnings` here. However if `a` were `@NonDet` this would not be sound. The error message doesn't give a way to differentiate the two and if `a` is not a parameter it could be difficult or impossible to tell what its type is without testing.

In invalid assignment statements and most other error messages, both the found and required types are specified and giving both in this error message would make the checker easier to use.

**Comment by t-rasmud** [comment]
Fixed in 2b13b384dac55843636152ebc0adbb1cc7c0953c
