### ISSUE TITLE
Annotations in extends clause don't affect valid types

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#56]
If a class `A` extends `@Det B`, then all instances of `A` should be instances of `@Det B`, thus it should be impossible to have `@NonDet A`.

Consider
```java
import org.checkerframework.checker.determinism.qual.*;

public class DetExtends extends @Det Object {
  public static void f(@NonDet DetExtends a) {
  }
}
```

This currently types check. This also applies to other checkers. Changing `@Det` to `@NonNull` and `@NonDet` to `@Nullable` results in the same thing.

**Comment by t-rasmud** [comment]
Same as checker framework bug - #2243.
