### ISSUE TITLE
JDK annotations should be @PolyDet of "up" or "down"

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#64]
In general, if a method takes a collection and its return type is not a collection, that type should be either `@PolyDet("up")` or `@PolyDet("down")`. This should also be the case if a parameter is of type `Object` because it could accept a collection.

This mainly applies to methods that will be overridden or implemented by unknown clients. The `Object` class in the JDK is an example. The `equals` and `toString` methods will often be `@PolyDet("up")` when implemented on collections or classes that use collections. Thus, to be as permissive as possible, these two methods should have return `@PolyDet("up")` rather than `@PolyDet`.

**Comment by t-rasmud** [comment]
Fixed in 8e396dbd786f3366f5357eb0366468a538120b1a
