### ISSUE TITLE
@PolyDet constructors allow @Det instances made with @NonDet params

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#68]
When a constructor's return type is `@PolyDet`, users can circumvent type checking constructor parameters, introducing unsoundness without a warning. Consider the following class:

```java
import org.checkerframework.checker.determinism.qual.*;

public class PolyConstructor {
    @PolyDet PolyConstructor(@PolyDet int i) {
    }

    static void f(@NonDet int i) {
        @Det PolyConstructor p = new @Det PolyConstructor(i);
    }
}
```

This code should not type check because we construct the `PolyConstructor` with a `@NonDet` parameter. Thus, `@PolyDet` should resolve to `@NonDet` and the constructed instance should be `@NonDet`. Adding `@Det` to the constructor invocation seems to override this. This is equivalent to writing `(@Det PolyConstructor) new PolyConstructor(i)`, which would be a downcast, this should at least issue a warning.

**Comment by t-rasmud** [comment]
Blocked on #2163

**Comment by t-rasmud** [comment]
Same as #2163.
