### ISSUE TITLE
Incorrect treatment of dot operator

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#7]
The checker seems to mark expressions that should be `@PolyDet` as `@NonDet` when they involve `this` or `super`. In one method that returns a call to another method `getString()`, simply using `getString()` is correctly marked as `@PolyDet` but using `this.getString()` is not.

Similarly, using `super.toString()` should be `@PolyDet` since it is marked that way in the Object class. However, it is flagged as `@NonDet`.

The classes are:
```
public class Foo {
    @Override
    public String toString() {
        return super.toString();
    }
}
```
and
```
public class Bar {
    public String toString() {
        return this.getString();
    }

    public String getString() {
        return "foo";
    }
}
```
The errors are:
```
Foo.java:8: error: [return.type.incompatible] incompatible types in return.
        return super.toString();
                             ^
  found   : @NonDet String
  required: @PolyDet String
```
and
```
Bar.java:15: error: [return.type.incompatible] incompatible types in return.
        return this.getString();
                             ^
  found   : @NonDet String
  required: @PolyDet String
```

The full errors are attached.
[Bar_errors.txt](https://github.com/t-rasmud/checker-framework/files/2142007/Bar_errors.txt)
[Foo_errors.txt](https://github.com/t-rasmud/checker-framework/files/2142008/Foo_errors.txt)

**Comment by t-rasmud** [comment]
This is a bug in the framework. Issue: [https://github.com/typetools/checker-framework/issues/2107](https://github.com/typetools/checker-framework/issues/2107)
