### ISSUE TITLE
Incorrect Random annotations in JDK

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#71]
The current annotations for `Random` are unsound. Consider
```java
public class TestRandom {
    public static void f(@Det Random r, @NonDet int seed) {
        r.setSeed(seed);
    }
}
```

This should not be allowed because afterward `r` is still `@Det`, even though though it was seeded with a random value. A similar problem holds with the `nextBytes` method.

**Comment by t-rasmud** [comment]
Fixed in 587a4422236461e70409339cb0932f74248d4574
