### ISSUE TITLE
Default return types with receivers

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#75]
In static methods, when there are no unannotated parameters, the return type defaults to `@Det` rather than `@PolyDet`. This currently doesn't apply to methods with receivers.

```java
import org.checkerframework.checker.determinism.qual.*;
import java.util.*;

public class ReturnTypeTest {
    String f(@Det ReturnTypeTest this) {
        return null;
    }

    static void g(@Det ReturnTypeTest a) {
        @Det String b = a.f();
    }
}
```
```
ReturnTypeTest.java:10: error: [assignment.type.incompatible] incompatible types in assignment.
        @Det String b = a.f();
                           ^
  found   : @NonDet String
  required: @Det String
```

The return type defaults to `@PolyDet` which resolves to `@NonDet` because there are no `@PolyDet` receivers. It should default to `@Det` because the same rule should apply to instance methods as static methods.

**Comment by t-rasmud** [comment]
Fixed in 803b0ab588e32dc7747d0d8ff94e406d25f39fbc
