### ISSUE TITLE
LinkedHashSet treated like HashSet.

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#79]
There are built in rules to handle constructing instances of `HashSet`. The checker checks these by seeing if the class being constructed is a subtype of `HashSet`. This means `LinedHashSet` is included, even though it has different rules.

Consider the following class
```java
import org.checkerframework.checker.determinism.qual.*;
import java.util.*;

public class LinkedHashSetTest {
    public static void f(@Det List<@Det String> c) {
        @Det Set<@Det String> s = new LinkedHashSet<@Det String>(c);
    }
}
```
I get this error
```
LinkedHashSetTest.java:6: error: [assignment.type.incompatible] incompatible types in assignment.
        @Det Set<@Det String> s = new LinkedHashSet<@Det String>(c);
                                  ^
  found   : @OrderNonDet LinkedHashSet<@Det String>
  required: @Det Set<@Det String>

```

This indicates that the `HashSet` rules are being used even though `LinkedHashSet` can be `@Det`, and in the JDK this method is annotated as `@PolyDet LinkedHashSet(@PolyDet Collection<? extends E>)`, so passing `@Det List` should create a `@Det LinkedHashSet`.

**Comment by t-rasmud** [comment]
Fixed in 7cd25a3.
