### ISSUE TITLE
Objects.hash is not @NonDet

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#81]
The `hashCode` method in `Object` is `@NonDet`. The `Objects` class has the `hashCode` and `hash` methods which wrap `hashCode`. These should be `@NonDet` as well. Consider the following class
```java
import org.checkerframework.checker.determinism.qual.*;
import java.util.*;

public class HashTest {
    public static void f() {
        @Det int c = Objects.hashCode(new Object());
    }
}
```
This class type checks, even though the hash code of this Object will change between runs. It could be fixed by adding the `Objects` class to the annotated JDK.

**Comment by t-rasmud** [comment]
Fixed in 5a8e89131b1b7d337a74cd411dcc2a97a8fcea20
