### ISSUE TITLE
Objects methods should be @PolyDet("up")

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#86]
In the `Object` class, most methods are `@PolyDet("up")` such as `equals` and `toString`. This is because an `Object` can be a Collection, which has the potential to be `@OrderNonDet`. In the new annotations for the `Objects` class, the return types are `@PolyDet` rather than `@PolyDet("up")`. The following methods need attention

- [equals](https://github.com/t-rasmud/checker-framework/blob/39ea9a711a3fd07574b2cec057f9837c7d40c221/checker/jdk/determinism/src/java/util/Objects.java#L60)
- [toString](https://github.com/t-rasmud/checker-framework/blob/39ea9a711a3fd07574b2cec057f9837c7d40c221/checker/jdk/determinism/src/java/util/Objects.java#L143)
- [compare](https://github.com/t-rasmud/checker-framework/blob/39ea9a711a3fd07574b2cec057f9837c7d40c221/checker/jdk/determinism/src/java/util/Objects.java#L184)

**Comment by t-rasmud** [comment]
Fixed in 39c30227e755c2e4059424e94c6562b4caa7a9b9
