### ISSUE TITLE
Array getClass always creates an error

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#89]
Consider this class
```java
import org.checkerframework.checker.determinism.qual.*;
import java.util.*;

public class ArrayGetClass {
    public static void f(@Det Object @Det [] arr) {
        Class<?> c = arr.getClass();
    }
}
```
I get the following error
```
ArrayGetClass.java:6: error: [invalid.array.component.type] component type (@Det) cannot be used with array type (@NonDet)
        Class<?> c = arr.getClass();
                                 ^
```
The returned class's type parameter should be the same as the Object that `getClass` was called on, which is a valid array type. So, this shouldn't be an error. I believe the issue is with the fact that the return type actually uses the erasure type, as described [here](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#getClass()). However, this is unique to arrays, the same problem doesn't occur with subtypes of `Collection`.

**Comment by t-rasmud** [comment]
Fixed in c4144b1918e04fadf45a27261c7ac8f3bed69edc
