### ISSUE TITLE
Exceptions can be tedious

### ISSUE THREAD

**Issue by JasonWaataja** [t-rasmud/checker-framework#9]
Any time errors relating to Exceptions are printed, the determinism checker flags them as `@NonDet`. This makes code that uses Exceptions hard to work with. For example:

```java
public class Exceptions {
    public int myParse(String num) {
        try {
            int n = Integer.parseInt(num);
            return n;
        } catch (NumberFormatException e) {
            System.out.println(e.toString());
            return 0;
        }
    }
}
```
This gives:
```
javac -processor DeterminismChecker Exceptions.java
Exceptions.java:7: error: [argument.type.incompatible] incompatible types in argument.
            System.out.println(e);
                               ^
  found   : @NonDet NumberFormatException
  required: @Det Object
1 error
```

One issue is that this could be deterministic (although I'm not sure how that could be found be the checker). Secondly, to suppress this warning, `e` must be cast to `@Det` some how. To do this requires creating an extra variable, or suppressing determinism for the whole method. These types of catch blocks often contain other printing, such as dumping parameters. Because parameters are usually `@PolyDet` this means the same treatment must be given to anything printed in catch blocks, which is very time consuming.

**Comment by t-rasmud** [comment]
Exception parameters default to @Det in commit [a942a2c5f882123172f6abac6b3ba508425e81e4]().
