### ISSUE TITLE
"cast" method in "Class.java" should have a different return type

### ISSUE THREAD

**Issue by jwaataja** [t-rasmud/checker-framework#95]
Consider the signature for `cast` in the JDK:
```java
public T cast(@PolyDet Class<T> this, @PolyDet Object obj)`.
```
I believe the return type of this method should be `@PolyDet T`. Since the return of this method is the same underlying object as `obj`, it will have the same determinism if the `Class<T>` receiver does as well. The `@PolyDet` return type would capture this. The determinism type of `T` is irrelevant since it's just being used to convert types.

**Comment by t-rasmud** [comment]
Fixed in 4fb8337888dac7552376a199f1d9fffec202d5fe
